# Generated by Django 5.0.6 on 2024-06-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_category_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='relations',
            field=models.ManyToManyField(blank=True, related_name='related_categories', to='category.category'),
        ),
    ]
