# Generated by Django 5.0.6 on 2024-06-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='relations',
            field=models.ManyToManyField(blank=True, to='category.category'),
        ),
    ]
