# Generated by Django 5.0.6 on 2024-06-03 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_category_relations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='relations',
            new_name='select_category',
        ),
    ]
