# Generated by Django 5.0.6 on 2024-06-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('add_a_category', models.CharField(max_length=100)),
                ('is_completed', models.BooleanField(default=False)),
                ('assign_date', models.DateField()),
            ],
        ),
    ]
